### ISSUE TITLE
font:width also in normal version?

### ISSUE THREAD

**Issue by Clevero** [dividuum/info-beamer#26]
i'm wondering why the method width for font objects is still only in info-beamer pi. why is this functionlity not available in the normal version?

**Comment by Clevero** [comment]
also is there a way to get the height of the text?

**Comment by dividuum** [comment]
font:width isn't available right now. I can add that tomorrow. The font height is about the size specified in the font:write parameter. If you output fonts at y=0 and y=height, they should not overlap.

**Comment by Clevero** [comment]
o_O wow, that was a really fast answer, that's awsome!!

thanks for the update :)
