### ISSUE TITLE
Mirrored image

### ISSUE THREAD

**Issue by half-pint** [dividuum/info-beamer#30]
I've installed info-beamer on an Arch Linux, using glfw-3.1.1-1. The image displayed is mirrored
![2015-08-12-183614_1024x768_scrot](https://cloud.githubusercontent.com/assets/3715068/9231680/ff22e7ba-4118-11e5-8b87-617b9ccc8708.png)
![2015-08-12-183702_1024x768_scrot](https://cloud.githubusercontent.com/assets/3715068/9231679/ff22967a-4118-11e5-9e3e-4607c15b934b.png)

**Comment by dividuum** [comment]
Sorry for the delay. Can you post the complete output of glxinfo?

**Comment by half-pint** [comment]
Thank you very much for your reply. http://paste.debian.net/292021/

**Comment by dividuum** [comment]
Thanks for the paste. The gallium driver again. I had another user with a similar problem, so there is a pattern somewhere. I'm not at home right now, so I can't do proper debugging, but I'll look into that mid of next week.

**Comment by half-pint** [comment]
That's cool, thanks very much for looking into that

**Comment by ignisf** [comment]
Experiencing the same oddity, `glxinfo` output -> https://gist.github.com/ignisf/55cc94fd2dcc072afa86

**Comment by ignisf** [comment]
It's fixed, thanks!

**Comment by dividuum** [comment]
Thanks for the feedback. That was an embarrassing bug :-\

**Comment by half-pint** [comment]
Thanks again! :)
