### ISSUE TITLE
cant run on native ubuntu 16.04

### ISSUE THREAD

**Issue by x29a** [dividuum/info-beamer#57]
hi,

im trying to run info-beamer opensource on a native ubuntu server 16.04 machine. I read somewhere, [that info-beamer can run without X](http://raspberrypi.stackexchange.com/a/33615/26266), or is this only valid for the rpi version?

i downloaded the prerequisites according to [the docs](https://info-beamer.com/doc/info-beamer#prerequisitesonubuntu) and built the software with debug via

> DEBUG="1" make

im logged in via ssh as root, the output i get is

> root@host:/opt/info-beamer# ./info-beamer samples/
> Info Beamer 1.0pre4.47a5ea+Lua 5.1 (http://info-beamer.org/)
> Copyright (c) 2015 Florian Wesch <fw@dividuum.de>
> 
> [main.c] chdir /opt/info-beamer
> [main.c] root node is samples
> [main.c] tcp/udp port is 4444
> CRITICAL ERROR: cannot initialize glfw

with the lua version beeing
> root@host:/opt/info-beamer# lua -v
> Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

and graphics hardware
> root@host:/opt/info-beamer# lspci | grep VGA
> 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV516 [Radeon X1300/X1550 Series]

after applying pull request #56 i see
> glfw error 65544 (X11: The DISPLAY environment variable is missing)

so X is required?

running [Xvfb](https://en.wikipedia.org/wiki/Xvfb) and exporting the display variable, i get
> root@host:/opt/info-beamer# export DISPLAY=:0
> ...
> glfw error 65544 (X11: RandR gamma ramp support seems broken)
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> [main.c] initial size is 1024x768
> glfw error 65545 (GLX: Failed to find a suitable GLXFBConfig)
> CRITICAL ERROR: cannot open window

After i install xorg, i get
> CRITICAL ERROR: need opengl 3.0 support

so i checked my openGL info
> root@host:/opt/info-beamer# glxinfo | grep -i "opengl"
> OpenGL vendor string: X.Org R300 Project
> OpenGL renderer string: Gallium 0.4 on ATI RV515
> OpenGL version string: 2.1 Mesa 12.0.6
> OpenGL shading language version string: 1.20
> OpenGL ES profile version string: OpenGL ES 2.0 Mesa 12.0.6
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16

what would be the minimal requirement to get similar behaviour to the rpi version? I dont want a desktop environment but have the system start directly into info-beamer.

**Comment by dividuum** [comment]
You'll probably need X, as I'm unaware of any hardware accelerated OpenGL implementation that doesn't use X on the Desktop. I might be wrong.

I suggest you use X, start one of those fullscreen window managers and then info-beamer. That should be pretty minimal.

**Comment by x29a** [comment]
Ok thanks, i installed XOrg, am starting the X server via rc.local and then info-beamer on top.

The openGL issue (similar to #41) is "fixed" by commenting the [opengl version check](https://github.com/dividuum/info-beamer/blob/master/main.c#L1566) out.
