### ISSUE TITLE
Can I use Open Source Version on Raspberry Pi ??

### ISSUE THREAD

**Issue by thanthdinesh** [dividuum/info-beamer#63]
Can I use Open Source Version on Raspberry Pi ??

**Comment by dividuum** [comment]
No. It uses OpenGL (which isn't available out of the box on the Pi) and doesn't use any kind of hardware accelerated video playback. Use [info-beamer pi](https://info-beamer.com/pi) if you want to run info-beamer nodes on a Raspberry.
