### ISSUE TITLE
Is the soruce code up to date?

### ISSUE THREAD

**Issue by heyjuvi** [dividuum/info-beamer#74]
I was wondering, if the sources are still up to date, since it does not compile without changes such as renaming `avcodec_alloc_frame` to `av_frame_alloc`.

(for comparability: I am using a recently updated version of Arch Linux, maybe this is just not a problem that occurs on a Raspbian system at the moment, anyway, maybe there should be a library version check to solve this)

**Comment by misterdanb** [comment]
Okay, sorry for the inconvenience, I just noticed that https://github.com/dividuum/info-beamer/pull/64 addresses the problems, so at least the problems listed in this issue can be seen as solved, if the pull request gets morged.
